apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-todo-app
  namespace: production
  labels:
    app: devops-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-todo-app
  template:
    metadata:
      labels:
        app: devops-todo-app
    spec:
      containers:
      - name: devops-todo-app
        image: your-account-id.dkr.ecr.us-east-1.amazonaws.com/devops-todo-app:1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
