apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-todo-app-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: todo.devops-learning.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-todo-app-svc
            port:
              number: 80
